name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        env: 
          INSIDERS: ${{ secrets.INSIDERS }}
        run: |
          pip install mkdocs-material
          pip install git+https://${INSIDERS}@github.com/davidsdesignserver/mkdocs-material-insiders.git
          pip install mkdocs-glightbox
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install pymdown-extensions pyyaml
          pip install "mkdocs-material[imaging]"
          pip install mkdocs-git-committers-plugin-2
          sudo apt-get install pngquant

      - name: Build and Deploy MkDocs
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_PAT }}
          CI: true
          INSIDERS: true
        run: |
          mkdocs build
          mkdocs gh-deploy --force
